/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dev.futurepath.views;

import dev.futurepath.calculator.core.IOManager;
import dev.futurepath.calculator.core.Operation;
import dev.futurepath.controller.CalculatorController;

/**
 *
 * @author Elena Cirstea
 */
public class CalculatorPanel extends javax.swing.JPanel  implements IOManager{
    private CalculatorController controller;
    /**
     * Creates new form CalculatorPanel
     */
    public CalculatorPanel() {
        initComponents();
        controller = new CalculatorController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sumBTN = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        firstValueTF = new javax.swing.JTextField();
        secondValueTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        sumBTN.setText("Sum");
        sumBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumBTNActionPerformed(evt);
            }
        });
        add(sumBTN);
        sumBTN.setBounds(229, 158, 65, 29);

        jLabel1.setText("First numer:");
        add(jLabel1);
        jLabel1.setBounds(30, 40, 87, 20);

        firstValueTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstValueTFActionPerformed(evt);
            }
        });
        add(firstValueTF);
        firstValueTF.setBounds(184, 40, 170, 26);

        secondValueTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondValueTFActionPerformed(evt);
            }
        });
        add(secondValueTF);
        secondValueTF.setBounds(190, 100, 160, 26);

        jLabel2.setText("Second number:");
        add(jLabel2);
        jLabel2.setBounds(30, 100, 130, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void sumBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumBTNActionPerformed
        // TODO add your handling code here:
        controller.sum();
    }//GEN-LAST:event_sumBTNActionPerformed

    private void firstValueTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstValueTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstValueTFActionPerformed

    private void secondValueTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondValueTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondValueTFActionPerformed

    @Override
    public void setResult(double d) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public double getResult() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public double getFirstValue() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public double getSecondValue() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void getFirstValue(double d) {
    }

    @Override
    public void getSecondValue(double d) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Operation getOperation() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setOperation(Operation oprtn) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField firstValueTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField secondValueTF;
    private javax.swing.JToggleButton sumBTN;
    // End of variables declaration//GEN-END:variables
}
