/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dev.futurepath.views;

import dev.futurepath.controllers.PlayerController;
import dev.futurepath.model.Player;
import javax.swing.JComboBox;

/**
 *
 * @author Elena Cirstea
 */
public class DeletePlayerPanel extends javax.swing.JPanel {
    //atributo
      private PlayerController controller;
    /**
     * Creates new form DeletePlayerPanel
     */
      //constructor
    public DeletePlayerPanel() {
        initComponents();
        controller = new PlayerController(this);
        controller.deletePlayer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        listPlayers = new javax.swing.JComboBox<>();
        deleteBTN = new javax.swing.JToggleButton();

        setLayout(null);

        jLabel1.setText("Player:");
        add(jLabel1);
        jLabel1.setBounds(20, 30, 100, 20);

        add(listPlayers);
        listPlayers.setBounds(120, 30, 210, 26);

        deleteBTN.setText("Delete");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });
        add(deleteBTN);
        deleteBTN.setBounds(140, 140, 77, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_deleteBTNActionPerformed

    public JComboBox<Player> getListPlayers() {
        return listPlayers;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton deleteBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<Player> listPlayers;
    // End of variables declaration//GEN-END:variables
}
